version: "3.7"
services:
  warehouse_db:
    container_name: warehouse_db
    image: "postgres:15.1"
    restart: always
    ports:
      - 5433:5432
    command: [ "postgres", "-c", "wal_level=logical" ]
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_PASSWORD: 16071607
      POSTGRES_USER: postgres
      PGPASSWORD: 16071607
  order_db:
    container_name: order_db
    image: "postgres:15.1"
    restart: always
    ports:
      - 5434:5432
    command: [ "postgres", "-c", "wal_level=logical" ]
    environment:
      POSTGRES_DB: order
      POSTGRES_PASSWORD: 16071607
      POSTGRES_USER: postgres
      PGPASSWORD: 16071607
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafdrop:
    container_name: kafdrop
    image: obsidiandynamics/kafdrop:latest
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
  debezium:
    image: debezium/connect:latest
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
    depends_on: [ kafka ]
    ports:
      - "8083:8083"
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on: [ kafka ]
    ports:
      - "8079:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092